// This file is auto-generated by @hey-api/openapi-ts

export type GetApiResponse = string;

export type GetApiError = unknown;

export type PostApiAuthenticationLoginData = {
  /**
   * The login payload needed to log a user in.
   */
  body: {
    email: string;
    password: string;
  };
};

export type PostApiAuthenticationLoginResponse = {
  id: string;
  email: string;
  active: boolean;
  role: "system_admin" | "admin" | "staff" | "business" | "collector";
  mfaEnabled: boolean;
  mfaVerified: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PostApiAuthenticationLoginError = {
  message: string;
};

export type PostApiAuthenticationLogoutResponse = string;

export type PostApiAuthenticationLogoutError = {
  message: string;
};

export type PostApiAuthenticationRegisterData = {
  /**
   * The user object of the user being registered.
   */
  body?: {
    email: string;
    password: string;
  };
};

export type PostApiAuthenticationRegisterResponse = {
  id: string;
  email: string;
  active: boolean;
  role: "system_admin" | "admin" | "staff" | "business" | "collector";
  mfaEnabled: boolean;
  mfaVerified: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PostApiAuthenticationRegisterError = {
  message: string;
};

export type GetApiAuthenticationCheckResponse = {
  id: string;
  email: string;
  active: boolean;
  role: "system_admin" | "admin" | "staff" | "business" | "collector";
  mfaEnabled: boolean;
  mfaVerified: boolean;
  createdAt: string;
  updatedAt: string;
};

export type GetApiAuthenticationCheckError = {
  message: string;
};

export type GetApiAuthenticationMfaEnableResponse = string;

export type GetApiAuthenticationMfaEnableError = {
  message: string;
};

export type PostApiAuthenticationMfaVerifyData = {
  /**
   * The verify payload needed to verify a users MFA authentication.
   */
  body: {
    code?: string;
  };
};

export type PostApiAuthenticationMfaVerifyResponse = string;

export type PostApiAuthenticationMfaVerifyError = {
  message: string;
};

export type PutApiAuthenticationPasswordResetData = {
  /**
   * The password reset payload.
   */
  body: {
    code: string;
    password: string;
    userId: string;
  };
};

export type PutApiAuthenticationPasswordResetResponse = string;

export type PutApiAuthenticationPasswordResetError = {
  message: string;
};

export type GetApiUsersData = {
  query?: {
    id?: string | null;
  };
};

export type GetApiUsersResponse =
  | {
      id: string;
      email: string;
      active: boolean;
      role: "system_admin" | "admin" | "staff" | "business" | "collector";
      mfaEnabled: boolean;
      mfaVerified: boolean;
      createdAt: string;
      updatedAt: string;
    }
  | Array<{
      id: string;
      email: string;
      active: boolean;
      role: "system_admin" | "admin" | "staff" | "business" | "collector";
      mfaEnabled: boolean;
      mfaVerified: boolean;
      createdAt: string;
      updatedAt: string;
    }>;

export type GetApiUsersError = {
  message: string;
};

export type PostApiUsersData = {
  /**
   * The new user object payload.
   */
  body: {
    email: string;
    password: string;
    role?: "system_admin" | "admin" | "staff" | "business" | "collector";
  };
};

export type PostApiUsersResponse = {
  id: string;
  email: string;
  active: boolean;
  role: "system_admin" | "admin" | "staff" | "business" | "collector";
  mfaEnabled: boolean;
  mfaVerified: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PostApiUsersError = {
  message: string;
};

export type PutApiUsersByIdData = {
  /**
   * The updated user object.
   */
  body?: {
    email: string;
    role?: "system_admin" | "admin" | "staff" | "business" | "collector";
  };
  path: {
    id: string;
  };
};

export type PutApiUsersByIdResponse = {
  id: string;
  email: string;
  active: boolean;
  role: "system_admin" | "admin" | "staff" | "business" | "collector";
  mfaEnabled: boolean;
  mfaVerified: boolean;
  createdAt: string;
  updatedAt: string;
};

export type PutApiUsersByIdError = {
  message: string;
};

export type DeleteApiUsersByIdData = {
  path: {
    id: string;
  };
};

export type DeleteApiUsersByIdResponse = string;

export type DeleteApiUsersByIdError = {
  message: string;
};

export type GetApiBusinessesData = {
  query?: {
    id?: string | null;
    includeUser?: "true" | "false" | "1" | "0";
  };
};

export type GetApiBusinessesResponse =
  | {
      id: string;
      name: string;
      type: "Recycler" | "Waste Collector" | "Buy Back Centre";
      description: string;
      phoneNumber: string;
      address: string;
      city: string;
      province: string;
      zipCode: string;
      userId: string;
      createdAt: string;
      updatedAt: string;
      user?: {
        id: string;
        email: string;
        active: boolean;
        role: "system_admin" | "admin" | "staff" | "business" | "collector";
        mfaEnabled: boolean;
        mfaVerified: boolean;
        createdAt: string;
        updatedAt: string;
      };
    }
  | Array<{
      id: string;
      name: string;
      type: "Recycler" | "Waste Collector" | "Buy Back Centre";
      description: string;
      phoneNumber: string;
      address: string;
      city: string;
      province: string;
      zipCode: string;
      userId: string;
      createdAt: string;
      updatedAt: string;
      user?: {
        id: string;
        email: string;
        active: boolean;
        role: "system_admin" | "admin" | "staff" | "business" | "collector";
        mfaEnabled: boolean;
        mfaVerified: boolean;
        createdAt: string;
        updatedAt: string;
      };
    }>;

export type GetApiBusinessesError = {
  message: string;
};

export type PostApiBusinessesData = {
  /**
   * The business object of the new business.
   */
  body: {
    name: string;
    type?: "Recycler" | "Waste Collector" | "Buy Back Centre";
    description: string;
    phoneNumber: string;
    address: string;
    city: string;
    province: string;
    zipCode: string;
    userId: string;
  };
};

export type PostApiBusinessesResponse = {
  id: string;
  name: string;
  type: "Recycler" | "Waste Collector" | "Buy Back Centre";
  description: string;
  phoneNumber: string;
  address: string;
  city: string;
  province: string;
  zipCode: string;
  userId: string;
  createdAt: string;
  updatedAt: string;
  user?: {
    id: string;
    email: string;
    active: boolean;
    role: "system_admin" | "admin" | "staff" | "business" | "collector";
    mfaEnabled: boolean;
    mfaVerified: boolean;
    createdAt: string;
    updatedAt: string;
  };
};

export type PostApiBusinessesError = {
  message: string;
};

export type PutApiBusinessesData = {
  /**
   * The business object for the updated business.
   */
  body?: {
    name: string;
    type?: "Recycler" | "Waste Collector" | "Buy Back Centre";
    description: string;
    phoneNumber: string;
    address: string;
    city: string;
    province: string;
    zipCode: string;
    userId: string;
  };
  query: {
    id: string;
  };
};

export type PutApiBusinessesResponse = {
  id: string;
  name: string;
  type: "Recycler" | "Waste Collector" | "Buy Back Centre";
  description: string;
  phoneNumber: string;
  address: string;
  city: string;
  province: string;
  zipCode: string;
  userId: string;
  createdAt: string;
  updatedAt: string;
  user?: {
    id: string;
    email: string;
    active: boolean;
    role: "system_admin" | "admin" | "staff" | "business" | "collector";
    mfaEnabled: boolean;
    mfaVerified: boolean;
    createdAt: string;
    updatedAt: string;
  };
};

export type PutApiBusinessesError = {
  message: string;
};

export type DeleteApiBusinessesData = {
  query: {
    id: string;
  };
};

export type DeleteApiBusinessesResponse = string;

export type DeleteApiBusinessesError = {
  message: string;
};

export type GetApiCollectorsData = {
  query?: {
    id?: string | null;
    includeUser?: "true" | "false" | "1" | "0";
  };
};

export type GetApiCollectorsResponse =
  | {
      id: string;
      firstName: string;
      lastName: string;
      idNumber: string;
      phoneNumber: string;
      address: string;
      city: string;
      province: string;
      zipCode: string;
      bankName: string;
      bankAccountHolder: string;
      bankAccountNumber: string;
      userId: string;
      createdAt: string;
      updatedAt: string;
      user?: {
        id: string;
        email: string;
        active: boolean;
        role: "system_admin" | "admin" | "staff" | "business" | "collector";
        mfaEnabled: boolean;
        mfaVerified: boolean;
        createdAt: string;
        updatedAt: string;
      };
    }
  | Array<{
      id: string;
      firstName: string;
      lastName: string;
      idNumber: string;
      phoneNumber: string;
      address: string;
      city: string;
      province: string;
      zipCode: string;
      bankName: string;
      bankAccountHolder: string;
      bankAccountNumber: string;
      userId: string;
      createdAt: string;
      updatedAt: string;
      user?: {
        id: string;
        email: string;
        active: boolean;
        role: "system_admin" | "admin" | "staff" | "business" | "collector";
        mfaEnabled: boolean;
        mfaVerified: boolean;
        createdAt: string;
        updatedAt: string;
      };
    }>;

export type GetApiCollectorsError = {
  message: string;
};

export type PostApiCollectorsData = {
  /**
   * The collector object of the new collector.
   */
  body?: {
    firstName: string;
    lastName: string;
    idNumber: string;
    phoneNumber: string;
    address: string;
    city: string;
    province: string;
    zipCode: string;
    bankName: string;
    bankAccountHolder: string;
    bankAccountNumber: string;
    userId: string;
  };
};

export type PostApiCollectorsResponse = {
  id: string;
  firstName: string;
  lastName: string;
  idNumber: string;
  phoneNumber: string;
  address: string;
  city: string;
  province: string;
  zipCode: string;
  bankName: string;
  bankAccountHolder: string;
  bankAccountNumber: string;
  userId: string;
  createdAt: string;
  updatedAt: string;
  user?: {
    id: string;
    email: string;
    active: boolean;
    role: "system_admin" | "admin" | "staff" | "business" | "collector";
    mfaEnabled: boolean;
    mfaVerified: boolean;
    createdAt: string;
    updatedAt: string;
  };
};

export type PostApiCollectorsError =
  | {
      message: string;
    }
  | {
      message: string;
    };

export type DeleteApiCollectorsData = {
  query: {
    id: string;
  };
};

export type DeleteApiCollectorsResponse = string;

export type DeleteApiCollectorsError = {
  message: string;
};

export type PutApiCollectorsData = {
  /**
   * The collector object for the updated collector.
   */
  body?: {
    firstName: string;
    lastName: string;
    idNumber: string;
    phoneNumber: string;
    address: string;
    city: string;
    province: string;
    zipCode: string;
    bankName: string;
    bankAccountHolder: string;
    bankAccountNumber: string;
    userId: string;
  };
  query: {
    id: string;
  };
};

export type PutApiCollectorsResponse = {
  id: string;
  firstName: string;
  lastName: string;
  idNumber: string;
  phoneNumber: string;
  address: string;
  city: string;
  province: string;
  zipCode: string;
  bankName: string;
  bankAccountHolder: string;
  bankAccountNumber: string;
  userId: string;
  createdAt: string;
  updatedAt: string;
  user?: {
    id: string;
    email: string;
    active: boolean;
    role: "system_admin" | "admin" | "staff" | "business" | "collector";
    mfaEnabled: boolean;
    mfaVerified: boolean;
    createdAt: string;
    updatedAt: string;
  };
};

export type PutApiCollectorsError =
  | {
      message: string;
    }
  | {
      message: string;
    };

export type GetApiProductsData = {
  query?: {
    id?: string | null;
    includeBusiness?: "true" | "false" | "1" | "0";
    includeBusinessUser?: "true" | "false" | "1" | "0";
  };
};

export type GetApiProductsResponse =
  | {
      id: string;
      name: string;
      price: string;
      gwCode: string;
      carbonFactor: string;
      businessId: string;
      createdAt: string;
      updatedAt: string;
      business?: {
        id: string;
        name: string;
        type: "Recycler" | "Waste Collector" | "Buy Back Centre";
        description: string;
        phoneNumber: string;
        address: string;
        city: string;
        province: string;
        zipCode: string;
        userId: string;
        createdAt: string;
        updatedAt: string;
        user?: {
          id: string;
          email: string;
          active: boolean;
          role: "system_admin" | "admin" | "staff" | "business" | "collector";
          mfaEnabled: boolean;
          mfaVerified: boolean;
          createdAt: string;
          updatedAt: string;
        };
      } | null;
    }
  | Array<{
      id: string;
      name: string;
      price: string;
      gwCode: string;
      carbonFactor: string;
      businessId: string;
      createdAt: string;
      updatedAt: string;
      business?: {
        id: string;
        name: string;
        type: "Recycler" | "Waste Collector" | "Buy Back Centre";
        description: string;
        phoneNumber: string;
        address: string;
        city: string;
        province: string;
        zipCode: string;
        userId: string;
        createdAt: string;
        updatedAt: string;
        user?: {
          id: string;
          email: string;
          active: boolean;
          role: "system_admin" | "admin" | "staff" | "business" | "collector";
          mfaEnabled: boolean;
          mfaVerified: boolean;
          createdAt: string;
          updatedAt: string;
        };
      } | null;
    }>;

export type GetApiProductsError = {
  message: string;
};

export type PostApiProductsData = {
  /**
   * The product object of the new product.
   */
  body: {
    name: string;
    price: string;
    gwCode: string;
    carbonFactor: string;
    businessId?: string | null;
  };
};

export type PostApiProductsResponse = {
  id: string;
  name: string;
  price: string;
  gwCode: string;
  carbonFactor: string;
  businessId: string;
  createdAt: string;
  updatedAt: string;
  business?: {
    id: string;
    name: string;
    type: "Recycler" | "Waste Collector" | "Buy Back Centre";
    description: string;
    phoneNumber: string;
    address: string;
    city: string;
    province: string;
    zipCode: string;
    userId: string;
    createdAt: string;
    updatedAt: string;
    user?: {
      id: string;
      email: string;
      active: boolean;
      role: "system_admin" | "admin" | "staff" | "business" | "collector";
      mfaEnabled: boolean;
      mfaVerified: boolean;
      createdAt: string;
      updatedAt: string;
    };
  } | null;
};

export type PostApiProductsError = {
  message: string;
};

export type DeleteApiProductsData = {
  query: {
    id: string;
  };
};

export type DeleteApiProductsResponse = string;

export type DeleteApiProductsError = {
  message: string;
};

export type PutApiProductsData = {
  /**
   * The product object for the updated product.
   */
  body?: {
    name: string;
    price: string;
    gwCode: string;
    carbonFactor: string;
    businessId?: string | null;
  };
  query: {
    id: string;
  };
};

export type PutApiProductsResponse = {
  id: string;
  name: string;
  price: string;
  gwCode: string;
  carbonFactor: string;
  businessId: string;
  createdAt: string;
  updatedAt: string;
  business?: {
    id: string;
    name: string;
    type: "Recycler" | "Waste Collector" | "Buy Back Centre";
    description: string;
    phoneNumber: string;
    address: string;
    city: string;
    province: string;
    zipCode: string;
    userId: string;
    createdAt: string;
    updatedAt: string;
    user?: {
      id: string;
      email: string;
      active: boolean;
      role: "system_admin" | "admin" | "staff" | "business" | "collector";
      mfaEnabled: boolean;
      mfaVerified: boolean;
      createdAt: string;
      updatedAt: string;
    };
  } | null;
};

export type PutApiProductsError = {
  message: string;
};

export type GetApiCollectionsData = {
  query?: {
    id?: string | null;
    includeBusiness?: "true" | "false" | "1" | "0";
    includeBusinessUser?: "true" | "false" | "1" | "0";
    includeCollector?: "true" | "false" | "1" | "0";
    includeCollectorUser?: "true" | "false" | "1" | "0";
    includeProduct?: "true" | "false" | "1" | "0";
    includeProductBusiness?: "true" | "false" | "1" | "0";
    includeProductBusinessUser?: "true" | "false" | "1" | "0";
  };
};

export type GetApiCollectionsResponse =
  | {
      id: string;
      businessId: string;
      collectorId: string;
      productId: string;
      weight: string;
      createdAt: string;
      updatedAt: string;
      business?: {
        id: string;
        name: string;
        type: "Recycler" | "Waste Collector" | "Buy Back Centre";
        description: string;
        phoneNumber: string;
        address: string;
        city: string;
        province: string;
        zipCode: string;
        userId: string;
        createdAt: string;
        updatedAt: string;
        user?: {
          id: string;
          email: string;
          active: boolean;
          role: "system_admin" | "admin" | "staff" | "business" | "collector";
          mfaEnabled: boolean;
          mfaVerified: boolean;
          createdAt: string;
          updatedAt: string;
        };
      } | null;
      collector?: {
        id: string;
        firstName: string;
        lastName: string;
        idNumber: string;
        phoneNumber: string;
        address: string;
        city: string;
        province: string;
        zipCode: string;
        bankName: string;
        bankAccountHolder: string;
        bankAccountNumber: string;
        userId: string;
        createdAt: string;
        updatedAt: string;
        user?: {
          id: string;
          email: string;
          active: boolean;
          role: "system_admin" | "admin" | "staff" | "business" | "collector";
          mfaEnabled: boolean;
          mfaVerified: boolean;
          createdAt: string;
          updatedAt: string;
        };
      } | null;
      product?: {
        id: string;
        name: string;
        price: string;
        gwCode: string;
        carbonFactor: string;
        businessId: string;
        createdAt: string;
        updatedAt: string;
        business?: {
          id: string;
          name: string;
          type: "Recycler" | "Waste Collector" | "Buy Back Centre";
          description: string;
          phoneNumber: string;
          address: string;
          city: string;
          province: string;
          zipCode: string;
          userId: string;
          createdAt: string;
          updatedAt: string;
          user?: {
            id: string;
            email: string;
            active: boolean;
            role: "system_admin" | "admin" | "staff" | "business" | "collector";
            mfaEnabled: boolean;
            mfaVerified: boolean;
            createdAt: string;
            updatedAt: string;
          };
        } | null;
      } | null;
    }
  | Array<{
      id: string;
      businessId: string;
      collectorId: string;
      productId: string;
      weight: string;
      createdAt: string;
      updatedAt: string;
      business?: {
        id: string;
        name: string;
        type: "Recycler" | "Waste Collector" | "Buy Back Centre";
        description: string;
        phoneNumber: string;
        address: string;
        city: string;
        province: string;
        zipCode: string;
        userId: string;
        createdAt: string;
        updatedAt: string;
        user?: {
          id: string;
          email: string;
          active: boolean;
          role: "system_admin" | "admin" | "staff" | "business" | "collector";
          mfaEnabled: boolean;
          mfaVerified: boolean;
          createdAt: string;
          updatedAt: string;
        };
      } | null;
      collector?: {
        id: string;
        firstName: string;
        lastName: string;
        idNumber: string;
        phoneNumber: string;
        address: string;
        city: string;
        province: string;
        zipCode: string;
        bankName: string;
        bankAccountHolder: string;
        bankAccountNumber: string;
        userId: string;
        createdAt: string;
        updatedAt: string;
        user?: {
          id: string;
          email: string;
          active: boolean;
          role: "system_admin" | "admin" | "staff" | "business" | "collector";
          mfaEnabled: boolean;
          mfaVerified: boolean;
          createdAt: string;
          updatedAt: string;
        };
      } | null;
      product?: {
        id: string;
        name: string;
        price: string;
        gwCode: string;
        carbonFactor: string;
        businessId: string;
        createdAt: string;
        updatedAt: string;
        business?: {
          id: string;
          name: string;
          type: "Recycler" | "Waste Collector" | "Buy Back Centre";
          description: string;
          phoneNumber: string;
          address: string;
          city: string;
          province: string;
          zipCode: string;
          userId: string;
          createdAt: string;
          updatedAt: string;
          user?: {
            id: string;
            email: string;
            active: boolean;
            role: "system_admin" | "admin" | "staff" | "business" | "collector";
            mfaEnabled: boolean;
            mfaVerified: boolean;
            createdAt: string;
            updatedAt: string;
          };
        } | null;
      } | null;
    }>;

export type GetApiCollectionsError = {
  message: string;
};

export type PostApiCollectionsData = {
  /**
   * The collection object of the new collection.
   */
  body: {
    collectorId: string;
    productId: string;
    weight: string;
    businessId?: string | null;
  };
};

export type PostApiCollectionsResponse = {
  id: string;
  businessId: string;
  collectorId: string;
  productId: string;
  weight: string;
  createdAt: string;
  updatedAt: string;
  business?: {
    id: string;
    name: string;
    type: "Recycler" | "Waste Collector" | "Buy Back Centre";
    description: string;
    phoneNumber: string;
    address: string;
    city: string;
    province: string;
    zipCode: string;
    userId: string;
    createdAt: string;
    updatedAt: string;
    user?: {
      id: string;
      email: string;
      active: boolean;
      role: "system_admin" | "admin" | "staff" | "business" | "collector";
      mfaEnabled: boolean;
      mfaVerified: boolean;
      createdAt: string;
      updatedAt: string;
    };
  } | null;
  collector?: {
    id: string;
    firstName: string;
    lastName: string;
    idNumber: string;
    phoneNumber: string;
    address: string;
    city: string;
    province: string;
    zipCode: string;
    bankName: string;
    bankAccountHolder: string;
    bankAccountNumber: string;
    userId: string;
    createdAt: string;
    updatedAt: string;
    user?: {
      id: string;
      email: string;
      active: boolean;
      role: "system_admin" | "admin" | "staff" | "business" | "collector";
      mfaEnabled: boolean;
      mfaVerified: boolean;
      createdAt: string;
      updatedAt: string;
    };
  } | null;
  product?: {
    id: string;
    name: string;
    price: string;
    gwCode: string;
    carbonFactor: string;
    businessId: string;
    createdAt: string;
    updatedAt: string;
    business?: {
      id: string;
      name: string;
      type: "Recycler" | "Waste Collector" | "Buy Back Centre";
      description: string;
      phoneNumber: string;
      address: string;
      city: string;
      province: string;
      zipCode: string;
      userId: string;
      createdAt: string;
      updatedAt: string;
      user?: {
        id: string;
        email: string;
        active: boolean;
        role: "system_admin" | "admin" | "staff" | "business" | "collector";
        mfaEnabled: boolean;
        mfaVerified: boolean;
        createdAt: string;
        updatedAt: string;
      };
    } | null;
  } | null;
};

export type PostApiCollectionsError = {
  message: string;
};

export type DeleteApiCollectionsData = {
  query: {
    id: string;
  };
};

export type DeleteApiCollectionsResponse = string;

export type DeleteApiCollectionsError = {
  message: string;
};

export type PutApiCollectionsData = {
  /**
   * The collection object for the updated collection.
   */
  body?: {
    collectorId: string;
    productId: string;
    weight: string;
    businessId?: string | null;
  };
  query: {
    id: string;
  };
};

export type PutApiCollectionsResponse = {
  id: string;
  businessId: string;
  collectorId: string;
  productId: string;
  weight: string;
  createdAt: string;
  updatedAt: string;
  business?: {
    id: string;
    name: string;
    type: "Recycler" | "Waste Collector" | "Buy Back Centre";
    description: string;
    phoneNumber: string;
    address: string;
    city: string;
    province: string;
    zipCode: string;
    userId: string;
    createdAt: string;
    updatedAt: string;
    user?: {
      id: string;
      email: string;
      active: boolean;
      role: "system_admin" | "admin" | "staff" | "business" | "collector";
      mfaEnabled: boolean;
      mfaVerified: boolean;
      createdAt: string;
      updatedAt: string;
    };
  } | null;
  collector?: {
    id: string;
    firstName: string;
    lastName: string;
    idNumber: string;
    phoneNumber: string;
    address: string;
    city: string;
    province: string;
    zipCode: string;
    bankName: string;
    bankAccountHolder: string;
    bankAccountNumber: string;
    userId: string;
    createdAt: string;
    updatedAt: string;
    user?: {
      id: string;
      email: string;
      active: boolean;
      role: "system_admin" | "admin" | "staff" | "business" | "collector";
      mfaEnabled: boolean;
      mfaVerified: boolean;
      createdAt: string;
      updatedAt: string;
    };
  } | null;
  product?: {
    id: string;
    name: string;
    price: string;
    gwCode: string;
    carbonFactor: string;
    businessId: string;
    createdAt: string;
    updatedAt: string;
    business?: {
      id: string;
      name: string;
      type: "Recycler" | "Waste Collector" | "Buy Back Centre";
      description: string;
      phoneNumber: string;
      address: string;
      city: string;
      province: string;
      zipCode: string;
      userId: string;
      createdAt: string;
      updatedAt: string;
      user?: {
        id: string;
        email: string;
        active: boolean;
        role: "system_admin" | "admin" | "staff" | "business" | "collector";
        mfaEnabled: boolean;
        mfaVerified: boolean;
        createdAt: string;
        updatedAt: string;
      };
    } | null;
  } | null;
};

export type PutApiCollectionsError = {
  message: string;
};

export type GetApiCollectionsExportData = {
  query?: {
    endDate?: string | null;
    startDate?: string | null;
  };
};

export type GetApiCollectionsExportResponse = string;

export type GetApiCollectionsExportError = {
  message: string;
};
