/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthenticationLoginImport } from './routes/authentication/login'
import { Route as AuthUsersIndexImport } from './routes/_auth/users/index'
import { Route as AuthenticationMfaVerifyImport } from './routes/authentication/mfa/verify'
import { Route as AuthenticationMfaEnableImport } from './routes/authentication/mfa/enable'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthenticationLoginRoute = AuthenticationLoginImport.update({
  id: '/authentication/login',
  path: '/authentication/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthUsersIndexRoute = AuthUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthenticationMfaVerifyRoute = AuthenticationMfaVerifyImport.update({
  id: '/authentication/mfa/verify',
  path: '/authentication/mfa/verify',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationMfaEnableRoute = AuthenticationMfaEnableImport.update({
  id: '/authentication/mfa/enable',
  path: '/authentication/mfa/enable',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/authentication/login': {
      id: '/authentication/login'
      path: '/authentication/login'
      fullPath: '/authentication/login'
      preLoaderRoute: typeof AuthenticationLoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/authentication/mfa/enable': {
      id: '/authentication/mfa/enable'
      path: '/authentication/mfa/enable'
      fullPath: '/authentication/mfa/enable'
      preLoaderRoute: typeof AuthenticationMfaEnableImport
      parentRoute: typeof rootRoute
    }
    '/authentication/mfa/verify': {
      id: '/authentication/mfa/verify'
      path: '/authentication/mfa/verify'
      fullPath: '/authentication/mfa/verify'
      preLoaderRoute: typeof AuthenticationMfaVerifyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/authentication/login': typeof AuthenticationLoginRoute
  '/': typeof AuthIndexRoute
  '/authentication/mfa/enable': typeof AuthenticationMfaEnableRoute
  '/authentication/mfa/verify': typeof AuthenticationMfaVerifyRoute
  '/users': typeof AuthUsersIndexRoute
}

export interface FileRoutesByTo {
  '/authentication/login': typeof AuthenticationLoginRoute
  '/': typeof AuthIndexRoute
  '/authentication/mfa/enable': typeof AuthenticationMfaEnableRoute
  '/authentication/mfa/verify': typeof AuthenticationMfaVerifyRoute
  '/users': typeof AuthUsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/authentication/login': typeof AuthenticationLoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/authentication/mfa/enable': typeof AuthenticationMfaEnableRoute
  '/authentication/mfa/verify': typeof AuthenticationMfaVerifyRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/authentication/login'
    | '/'
    | '/authentication/mfa/enable'
    | '/authentication/mfa/verify'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/authentication/login'
    | '/'
    | '/authentication/mfa/enable'
    | '/authentication/mfa/verify'
    | '/users'
  id:
    | '__root__'
    | '/_auth'
    | '/authentication/login'
    | '/_auth/'
    | '/authentication/mfa/enable'
    | '/authentication/mfa/verify'
    | '/_auth/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticationLoginRoute: typeof AuthenticationLoginRoute
  AuthenticationMfaEnableRoute: typeof AuthenticationMfaEnableRoute
  AuthenticationMfaVerifyRoute: typeof AuthenticationMfaVerifyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticationLoginRoute: AuthenticationLoginRoute,
  AuthenticationMfaEnableRoute: AuthenticationMfaEnableRoute,
  AuthenticationMfaVerifyRoute: AuthenticationMfaVerifyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/authentication/login",
        "/authentication/mfa/enable",
        "/authentication/mfa/verify"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/",
        "/_auth/users/"
      ]
    },
    "/authentication/login": {
      "filePath": "authentication/login.tsx"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/authentication/mfa/enable": {
      "filePath": "authentication/mfa/enable.tsx"
    },
    "/authentication/mfa/verify": {
      "filePath": "authentication/mfa/verify.tsx"
    },
    "/_auth/users/": {
      "filePath": "_auth/users/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
